# We want to make sure that a user is able to build the docs locally before pushing to RTD.
# Additionally, this helps us to better determine if there is an issue with the RTD build 
# versus an issue with sphinx and mkdocs itself.
name: Build Docs with Actions

on:
    push:
        branches:
            - '**'

jobs:
    build-install:
        runs-on: ${{ matrix.os }}
        strategy:
          matrix:
            os: [ubuntu-latest]
            # we only use 3.9 for RTD at this time.
            python-version: ["3.9"]

        steps:
          - name: Checkout repository
            uses: actions/checkout@v2

          - name: Set up Python
            uses: actions/setup-python@v2
            with:
              python-version: ${{ matrix.python-version }}

          - name: Check python3 == python${{ matrix.python-version }}
            run: |
              installed_python=$(python3 --version)
              echo "Installed Python: $installed_python"
              if [[ "$installed_python" != *"${{ matrix.python-version }}"* ]]; then
                echo "Python version mismatch. Expected: ${{ matrix.python-version }}, but got: $installed_python"
                exit 1
              fi

          - name: Install Dependencies
            run: |
                python3 -m pip install -e .[dev]

          - name: Build Docs
            run: make docs
